Implement Routing
dominikszczuka/ToDo pull request #6
Opened 2020-12-07 11:07 UTC by dominikszczuka

2020-12-07 14:48 UTC, wikson13 commented
Please use correct naming convention for pull request (like first pull request)

2020-12-07 14:55 UTC, wikson13 commented on src/Components/Nav/Nav.tsx
> +  const links: LinkElements[] = [
Please try to be consistent with interfaces name. The There is array of string[] not strings[], number[] not numbers[].

2020-12-07 15:01 UTC, wikson13 commented on src/Components/Nav/Nav.tsx
>        title: `${t("menu.pos2")}`,
Please use other naming convention. The naming like pos1, pos2 is not clear and if you want to change order of items there will be a lot of changes.

2020-12-07 15:04 UTC, wikson13 commented on src/navigation/RootNavigator/RootNavigator.tsx
> +        <Route path="/history" component={HistoryScreen} />
You can add Route for other paths. Something like 404 page

2020-12-07 15:06 UTC, wikson13 commented on src/constants/types/Link.ts
> +export interface LinkElements {
Please change naming convention. ([2,5,7] => [number,number,number] not [numbers, numbers, numbers]

2020-12-07 15:06 UTC, wikson13 requested changes
Please read comments

2020-12-07 16:11 UTC, wikson13 commented
Please dont't merge before we accept cr changes

2020-12-08 17:18 UTC, MRadek55 approved these changes

2020-12-08 17:51 UTC, wikson13 approved these changes

2020-12-09 07:00 UTC, merged